version: '3.9'  # Elimina esta línea (Docker ya no requiere 'version')
services:
  java_api:
    container_name: java_api_container
    image: java_api_image
    build: .
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projectfinalspringtodocode?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - USER_DB=${DB_USER}
      - PASSWORD_DB=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  mysql:
    container_name: mysql_container
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=projectfinalspringtodocode
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: